# Generated by Django 4.2.4 on 2023-09-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitType', models.IntegerField(choices=[(0, 'HouseTour'), (1, 'TestDrive')], default=0)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
    ]
