# Generated by Django 4.2.4 on 2023-09-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarType', models.IntegerField(choices=[(0, 'CalendarUser'), (1, 'CalendarProperty')], default=0)),
                ('visits', models.ManyToManyField(to='visit.visit')),
            ],
        ),
    ]
