# Generated by Django 4.2.4 on 2023-09-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarProperty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('photos', models.ImageField(upload_to=None)),
                ('mileage', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('motor', models.CharField(max_length=255)),
                ('calendarProperty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendarProperty.calendar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('photos', models.ImageField(upload_to=None)),
                ('squareMetters', models.IntegerField()),
                ('stratus', models.IntegerField()),
                ('roomsNumber', models.IntegerField()),
                ('bathsNumber', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('calendarProperty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendarProperty.calendar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
